[book]
authors = ["xieby1"]
language = "en"
multilingual = false
src = "docs/"
title = "ChiselAIA"

[output.html]
git-repository-url = "https://github.com/OpenXiangShan-Nanhu/ChiselAIA"
mathjax-support = true
