[book]
authors = ["xieby1"]
language = "en"
multilingual = false
src = "docs/"
title = "OpenAIA.scala"

[output.html]
git-repository-url = "https://github.com/OpenXiangShan-Nanhu/OpenAIA.scala"
mathjax-support = true
